import { Lesson, MapAsset } from './types';

export const FALLBACK_SVG = `data:image/svg+xml;utf8,${encodeURIComponent(
  `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1200 400'>
    <defs>
      <linearGradient id='g' x1='0' x2='1' y1='0' y2='1'>
        <stop offset='0%' stop-color='#eff6ff'/>
        <stop offset='100%' stop-color='#e0f2fe'/>
      </linearGradient>
    </defs>
    <rect width='1200' height='400' fill='url(#g)'/>
    <g fill='none' stroke='#2563eb' stroke-width='2' opacity='0.35'>
      <path d='M0,260 Q200,180 400,230 T800,220 T1200,240'/>
      <path d='M0,300 Q250,260 500,290 T1000,280 T1200,300'/>
    </g>
    <text x='50%' y='50%' dominant-baseline='middle' text-anchor='middle' font-family='system-ui, sans-serif' font-size='28' fill='#1f2937'>Map preview</text>
    <text x='50%' y='58%' dominant-baseline='middle' text-anchor='middle' font-family='system-ui, sans-serif' font-size='14' fill='#4b5563'>Fallback image (no network needed)</text>
  </svg>`
)}`;

export const MOCK_LESSONS: Lesson[] = [
  {
    id: "l1",
    title: "Ancient Rome: Forum & Temples",
    author: "Interactive Bulgaria Foundation",
    tags: ["History", "Ancient Rome", "VR Ready", "Architecture", "Italy", "Educational", "360 Tour"],
    language: "EN",
    level: "Intermediate",
    rating: 4.8,
    favorites: 812,
    thumb: "https://images.unsplash.com/photo-1544989164-31dc3c645987?q=80&w=1200&auto=format&fit=crop",
    location: { country: "Italy", city: "Rome" },
  },
  {
    id: "l2",
    title: "Bulgarian Revival Architecture",
    author: "SENA Competence Center",
    tags: ["Architecture", "Culture", "360°", "Bulgaria", "Historic", "Revival"],
    language: "BG",
    level: "Beginner",
    rating: 4.6,
    favorites: 421,
    thumb: "https://images.unsplash.com/photo-1519682577862-22b62b24e493?q=80&w=1200&auto=format&fit=crop",
    location: { country: "Bulgaria", city: "Koprivshtitsa" },
  },
  {
    id: "l3",
    title: "Marine Ecosystems: Coastal Dunes",
    author: "AI Resource Center",
    tags: ["Biology", "Environment", "Quiz", "Nature", "Greece", "Coastal"],
    language: "EN",
    level: "Advanced",
    rating: 4.9,
    favorites: 1021,
    thumb: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop",
    location: { country: "Greece", city: "Lefkada" },
  },
  {
    id: "l4",
    title: "Vienna: Baroque Palace Symbols",
    author: "European School Brussels IV",
    tags: ["Art", "Baroque", "Symbols", "Vienna", "Austria", "Palace"],
    language: "EN",
    level: "Intermediate",
    rating: 4.7,
    favorites: 593,
    thumb: "https://images.unsplash.com/photo-1544829728-e5cb9eedf658?q=80&w=1200&auto=format&fit=crop",
    location: { country: "Austria", city: "Vienna" },
  },
];

export const MOCK_USER_ID = "user_01";

export const MOCK_MAP_ASSETS: MapAsset[] = [
  {
    id: "ma1",
    title: "Old Town, Koprivshtitsa",
    author: "SENA Competence Center",
    authorId: "user_02",
    tags: ["Architecture", "Culture", "360°", "Bulgaria", "Historic", "Revival"],
    description: "A panoramic view of the iconic architecture in Koprivshtitsa, showcasing the Bulgarian Revival period.",
    thumb: "https://images.unsplash.com/photo-1519682577862-22b62b24e493?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma2",
    title: "Explore the heart of ancient Rome.",
    author: "Interactive Bulgaria Foundation",
    authorId: "user_01",
    tags: ["History", "Ancient Rome", "VR Ready", "Italy", "Ruins", "Forum"],
    description: "This 360° image captures the remaining columns and structures of the Forum, the center of day-to-day life in ancient Rome.",
    thumb: "https://images.unsplash.com/photo-1544989164-31dc3c645987?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma3",
    title: "Coastal Dunes of Lefkada",
    author: "AI Resource Center",
    authorId: "user_03",
    tags: ["Biology", "Environment", "Greece", "Dunes", "Coastal", "Nature"],
    description: "A serene 360° view of the coastal dunes and turquoise waters of Lefkada, Greece. An ideal asset for environmental studies.",
    thumb: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma4",
    title: "Belvedere Palace, Vienna",
    author: "European School Brussels IV",
    authorId: "user_04",
    tags: ["Art", "Baroque", "Austria", "Vienna", "Palace", "Museum"],
    description: "A stunning panoramic shot of the Belvedere Palace in Vienna, a masterpiece of Baroque architecture.",
    thumb: "https://images.unsplash.com/photo-1544829728-e5cb9eedf658?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma5",
    title: "My Secret Garden Spot",
    author: "Interactive Bulgaria Foundation",
    authorId: "user_01",
    tags: ["Personal", "Nature", "Quiet", "Garden", "Green", "Relax"],
    description: "A personal 360° image from my private garden. Not for public use.",
    thumb: "https://images.unsplash.com/photo-1444090542259-0af8fa96557e?q=80&w=800&auto=format&fit=crop",
    visibility: "Private",
  },
  {
    id: "ma6",
    title: "Eiffel Tower Summit View",
    author: "France Tours 360",
    authorId: "user_05",
    tags: ["Paris", "France", "Eiffel Tower", "Cityscape", "360°"],
    description: "A breathtaking 360° panoramic view from the top of the Eiffel Tower, overlooking the city of Paris.",
    thumb: "https://images.unsplash.com/photo-1502602898657-3e91760c0341?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma7",
    title: "Louvre Museum Pyramid",
    author: "Art Explorers",
    authorId: "user_06",
    tags: ["Paris", "France", "Louvre", "Art", "Museum", "Architecture"],
    description: "The iconic glass pyramid entrance to the Louvre Museum, captured in a stunning 360° photo.",
    thumb: "https://images.unsplash.com/photo-1599227285918-a6e753fb4c1f?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma8",
    title: "Notre-Dame Cathedral Interior",
    author: "Historic Journeys",
    authorId: "user_07",
    tags: ["Paris", "France", "Notre Dame", "Cathedral", "Gothic", "Architecture"],
    description: "A pre-fire 360° view of the awe-inspiring interior of the Notre-Dame Cathedral.",
    thumb: "https://images.unsplash.com/photo-1556008953-b99f81603799?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma9",
    title: "Streets of Montmartre",
    author: "France Tours 360",
    authorId: "user_05",
    tags: ["Paris", "France", "Montmartre", "Art", "Street View"],
    description: "Wander the charming and artistic streets of Montmartre in this immersive 360° experience.",
    thumb: "https://images.unsplash.com/photo-1529138499273-6a972c2b39a3?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma10",
    title: "Tower Bridge, London",
    author: "UK Panoramas",
    authorId: "user_08",
    tags: ["London", "UK", "Tower Bridge", "Cityscape", "River Thames"],
    description: "A classic 360° view of the Tower Bridge from the bank of the River Thames.",
    thumb: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma11",
    title: "Buckingham Palace Gates",
    author: "UK Panoramas",
    authorId: "user_08",
    tags: ["London", "UK", "Buckingham Palace", "Royalty", "Historic", "England"],
    description: "Stand before the grand gates of Buckingham Palace in this royal 360° image.",
    thumb: "https://images.unsplash.com/photo-1517866345380-4916a23c1a6b?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma12",
    title: "British Museum Great Court",
    author: "Art Explorers",
    authorId: "user_06",
    tags: ["London", "UK", "British Museum", "Museum", "Architecture"],
    description: "The magnificent glass roof of the Great Court at the British Museum in a 360° photograph.",
    thumb: "https://images.unsplash.com/photo-1589952285214-3a5e11f18b57?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma13",
    title: "Brandenburg Gate",
    author: "German Vistas",
    authorId: "user_09",
    tags: ["Berlin", "Germany", "Brandenburg Gate", "History", "Monument"],
    description: "A 360° view of the iconic Brandenburg Gate, a symbol of German reunification.",
    thumb: "https://images.unsplash.com/photo-1599935399745-0818c7c1a847?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma14",
    title: "Reichstag Building Dome",
    author: "German Vistas",
    authorId: "user_09",
    tags: ["Berlin", "Germany", "Reichstag", "Architecture", "Politics"],
    description: "Look out over Berlin from inside the modern glass dome of the Reichstag Building.",
    thumb: "https://images.unsplash.com/photo-1540998145399-a5438a0f531d?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma15",
    title: "Berlin Wall Memorial",
    author: "Historic Journeys",
    authorId: "user_07",
    tags: ["Berlin", "Germany", "Berlin Wall", "History", "Cold War"],
    description: "A somber 360° perspective of the preserved section of the Berlin Wall at the Bernauer Strasse memorial.",
    thumb: "https://images.unsplash.com/photo-1549504535-1f636c64368a?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma16",
    title: "Royal Palace of Madrid",
    author: "España 360",
    authorId: "user_10",
    tags: ["Madrid", "Spain", "Palace", "Royalty", "Architecture"],
    description: "A majestic 360° view of the sprawling Royal Palace of Madrid from the Plaza de la Armería.",
    thumb: "https://images.unsplash.com/photo-1595701822245-1c5c1f6c449c?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma17",
    title: "Prado Museum Hall",
    author: "Art Explorers",
    authorId: "user_06",
    tags: ["Madrid", "Spain", "Prado Museum", "Art", "Museum"],
    description: "An immersive 360° look inside one of the grand halls of the world-renowned Prado Museum.",
    thumb: "https://images.unsplash.com/photo-1581430981014-a3c1044b7d19?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma18",
    title: "El Retiro Park Lake",
    author: "España 360",
    authorId: "user_10",
    tags: ["Madrid", "Spain", "Retiro Park", "Nature", "Park", "Cityscape"],
    description: "A tranquil 360° scene by the lake in El Retiro Park, with the Alfonso XII monument in the background.",
    thumb: "https://images.unsplash.com/photo-1563725991-235852179839?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma19",
    title: "Rijksmuseum, Amsterdam",
    author: "Dutch Panoramas",
    authorId: "user_11",
    tags: ["Amsterdam", "Netherlands", "Rijksmuseum", "Museum", "Art"],
    description: "A 360° view of the stunning architecture of the Rijksmuseum in Amsterdam's Museum Square.",
    thumb: "https://images.unsplash.com/photo-1589883633634-386b038c1a6b?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma20",
    title: "Canals of Amsterdam",
    author: "Dutch Panoramas",
    authorId: "user_11",
    tags: ["Amsterdam", "Netherlands", "Canal", "Cityscape", "Historic"],
    description: "A quintessential 360° view of the picturesque canals and historic houses of Amsterdam.",
    thumb: "https://images.unsplash.com/photo-1528271537-646763845507?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma21",
    title: "The Acropolis of Athens",
    author: "Historic Journeys",
    authorId: "user_07",
    tags: ["Athens", "Greece", "Acropolis", "Parthenon", "History", "Ancient Greece"],
    description: "A sweeping 360° vista of the Acropolis, crowned by the magnificent Parthenon.",
    thumb: "https://images.unsplash.com/photo-1585255470434-321271121cea?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma22",
    title: "View from Lycabettus Hill",
    author: "AI Resource Center",
    authorId: "user_03",
    tags: ["Athens", "Greece", "Cityscape", "Panorama", "Sunset"],
    description: "A 360° panoramic view of Athens at sunset from the top of Lycabettus Hill, with the Acropolis in the distance.",
    thumb: "https://images.unsplash.com/photo-1602066223215-772a59b3259e?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  {
    id: "ma23",
    title: "Champs de Mars Picnic",
    author: "France Tours 360",
    authorId: "user_05",
    tags: ["Paris", "France", "Eiffel Tower", "Park", "360°"],
    description: "A lovely 360° view from a picnic on the Champs de Mars, looking up at the Eiffel Tower.",
    thumb: "https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=800&auto=format&fit=crop",
    visibility: "Public",
  },
  // START: Added for stacked marker test
  {
    id: "ma24",
    title: "Eiffel Tower - View from Below",
    author: "France Tours 360", authorId: "user_05", tags: ["Paris", "France", "Eiffel Tower", "Architecture", "Landmark"],
    description: "Looking up at the intricate iron lattice of the Eiffel Tower from directly underneath.",
    thumb: "https://images.unsplash.com/photo-1543208436-4c38c6543525?q=80&w=800",
    visibility: "Public",
  },
  {
    id: "ma25",
    title: "Eiffel Tower - Night Sparkle",
    author: "France Tours 360", authorId: "user_05", tags: ["Paris", "France", "Eiffel Tower", "Night", "Lights"],
    description: "The Eiffel Tower shimmering with golden lights at night.",
    thumb: "https://images.unsplash.com/photo-1528213605396-2216e91a36a2?q=80&w=800",
    visibility: "Public",
  },
  {
    id: "ma26",
    title: "Eiffel Tower from Trocadéro",
    author: "France Tours 360", authorId: "user_05", tags: ["Paris", "France", "Eiffel Tower", "Gardens", "Viewpoint"],
    description: "The classic viewpoint of the Eiffel Tower from the Jardins du Trocadéro.",
    thumb: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?q=80&w=800",
    visibility: "Public",
  },
  {
    id: "ma27",
    title: "Carousel near Eiffel Tower",
    author: "Art Explorers", authorId: "user_06", tags: ["Paris", "France", "Eiffel Tower", "Carousel", "Romantic", "Park"],
    description: "A vintage carousel with the Eiffel Tower in the background.",
    thumb: "https://images.unsplash.com/photo-1570597129033-314d33434689?q=80&w=800",
    visibility: "Public",
  },
  {
    id: "ma28",
    title: "Pont de Bir-Hakeim View",
    author: "France Tours 360", authorId: "user_05", tags: ["Paris", "France", "Eiffel Tower", "Bridge", "Cityscape", "Seine"],
    description: "A view of the Eiffel Tower from the famous Pont de Bir-Hakeim bridge.",
    thumb: "https://images.unsplash.com/photo-1575218823251-6834479543e2?q=80&w=800",
    visibility: "Public",
  },
  {
    id: "ma29",
    title: "Eiffel Tower in Spring",
    author: "France Tours 360", authorId: "user_05", tags: ["Paris", "France", "Eiffel Tower", "Spring", "Blossoms", "Nature"],
    description: "The Eiffel Tower surrounded by blooming cherry blossoms in the spring.",
    thumb: "https://images.unsplash.com/photo-1555531835-36a51c72a884?q=80&w=800",
    visibility: "Public",
  },
  {
    id: "ma30",
    title: "Seine River Cruise View",
    author: "Historic Journeys", authorId: "user_07", tags: ["Paris", "France", "Eiffel Tower", "River", "Cruise", "Boat"],
    description: "Viewing the Eiffel Tower from a boat on the Seine River.",
    thumb: "https://images.unsplash.com/photo-1522549223126-f463b39a3bd2?q=80&w=800",
    visibility: "Public",
  },
  {
    id: "ma31",
    title: "Eiffel Tower Detail",
    author: "Art Explorers", authorId: "user_06", tags: ["Paris", "France", "Eiffel Tower", "Architecture", "Ironwork", "Detail"],
    description: "A close-up shot of the architectural details of the Eiffel Tower's ironwork.",
    thumb: "https://images.unsplash.com/photo-1570699043103-108210350a41?q=80&w=800",
    visibility: "Public",
  },
  {
    id: "ma32",
    title: "Rue de l'Université",
    author: "France Tours 360", authorId: "user_05", tags: ["Paris", "France", "Eiffel Tower", "Street View", "Perspective", "City"],
    description: "A classic street view of the Eiffel Tower from Rue de l'Université.",
    thumb: "https://images.unsplash.com/photo-1534299329241-862d2110fb26?q=80&w=800",
    visibility: "Public",
  },
  {
    id: "ma33",
    title: "Eiffel Tower - Private Balcony",
    author: "Interactive Bulgaria Foundation", authorId: "user_01", tags: ["Paris", "France", "Eiffel Tower", "Apartment", "View", "Balcony"],
    description: "A private view of the Eiffel Tower from a nearby apartment balcony.",
    thumb: "https://images.unsplash.com/photo-16060518843-a68586f1a8e0?q=80&w=800",
    visibility: "Private",
  },
  // END: Added for stacked marker test
];

export const QA: Array<{ q: string; a: string }> = [
  { q: "Is Study360 free?", a: "Yes. All assets are free for educational use. Copyright stays with authors." },
  { q: "Can I use public images from the map in my lessons?", a: "Yes, you can build lessons using public map assets or your own uploads." },
  { q: "How do I embed a lesson?", a: "After publishing, copy the link or iframe and paste it into Moodle, Google Sites, or any website." },
  { q: "Which file types can I upload?", a: "360° images (.jpg) and 360° videos (.mp4) are supported in this mock." },
];